### PR TITLE
Fixed broken keepalive. Unwanted pattern passes RE_PRECEDING

### PR DESCRIPTION
**Pull request by biggeleben**
Dovecot might answer DONE with some statistics: "IDLE OK Idle completed (0.001 + 0.093 + 0.092 secs)." The plus character passes RE_PRECEDING which runs into a dead end code-wise.

### CODE REVIEW

**Comment by biggeleben** [comment]
Just saw that #564 is identical. Personally I'd prefer my variant of the regex because IMO it's clearer. However, @surajwy added a test-case. Maybe can integrate both requests.

Independent of that, It would be really helpful to get that change because it took a hell of time to finally figure out why existing unchanged code stopped working from one day to another. Apparently, it was a config change on the dovecot server that introduces command stats.

**Comment by foudfou** [comment]
This has been holding me back from upgrading dovecot...
The original regex does look kinda convoluted.
@biggeleben why don't you add  #564's test, so this can be merged soon ?

**Comment by biggeleben** [comment]
Yep, added the missing test case.

**Comment by silverwind** [comment]
@mscdex can we see this merged and released? I can confirm it fixes #580.

**Comment by mscdex** [comment]
Landed in 941b071. Thanks!

**Pull request closed without merging**
