### PR TITLE
substituted undefined config with self._config

### PR DESCRIPTION
**Pull request by parro-it**
It appear to affect only starttls connection.
After the change, I can successfully connect.

I don't add test because I'm not able to successfully run existing ones...

### CODE REVIEW

**Comment by sterlingwes** [comment]
+1 pls merge

**Comment by NAlexandrov** [comment]
+1

**Comment by atiertant** [comment]
+1 this correct: 

    node_modules/imap/lib/Connection.js:1700
        self._sock.setTimeout(config.socketTimeout);
                              ^
    ReferenceError: config is not defined

**Comment by mscdex** [comment]
Landed in 2373af9e7. Thanks!

**Comment by parro-it** [comment]
You're welcome!

**Pull request closed without merging**
